export const DNI_EMPLOYEE_SECOND = '10346833';
export const FULL_NAME_SECOND_EMPLOYEE = 'MARIA ESTELA GUILLEN CUBA';
export const DNI_EMPLOYEE_PRIMARY = '42933662';
export const FULL_NAME_PRIMARY_EMPLOYEE = 'CATHERINE SUSAN CHANG LÓPEZ';
